### ISSUE TITLE
[Concern] Closed Source

### ISSUE THREAD

**Issue by DarkCrypt** [yogesh-hacker/hackflix.github.io#1]
Hack Flix appears to be a copy of [Cineapp](https://github.com/vendz/Cineapp) with added enhancements and features. Hench the mention within Cineapp's repo to gain users.

Unfortunately, Hack Flix is **closed source**.

It's understandable for certain reasons to keep an app closed source but this also raises immediate security concerns and skepticism. Because of this decision, most (if not all) GitHub users will NOT use this app. GitHub users love the open source community and prefer to use open source software for obvious reasons.

_*Note:_ You should also give credit to Cineapp and post this for users to see within your repo.

**Comment by yogesh-hacker** [comment]
Sorry, but do not copy any content from you not your layout, not your video player or nor your content.

As you can't disclose your sources much like that I disclose my sources.

It's a copy of your app because...

1. Your app doesn't have a in-built video player like me though I can ready to give credit that video player inspired by MX Player.
2. Your app embeds others not streams
3. Your app uses MySQL or SQL database but mine Firebase.


Listen bro my app has many features and didn't copied anything from. Because each movie apps are similar... I also found that someone copied mine, I leave him because the designs ideas may be similar.

**Comment by DarkCrypt** [comment]
To be perfectly clear, Cineapp is not my app nor am I the dev. I've only submitted feedback and feature requests to that repo because the app is severely lacking in quality.

No need to apologize for defending your app, you have every right to do so and I commend you. I apologize for my post appearing as an attack and also for my assumptions. I was meaning to attempt to express my closed source concern which I'll stand behind. I'll also give you the "benefit of the doubt" for your app not copying Cineapp even though your code can't be reviewed by others. You're also correct about movie apps having many similarities and common design concepts.

I understand your list of 3 arguments between the 2 apps but they only hold value since it's obvious to see that Cineapp is a dead app without any support from the dev for months. The app would've had many improvements if this wasn't the case (in-app video player, direct streams instead of crappy embeds, quality sources, etc.).

Your app being closed source is still a major security/privacy concern which is undeniable but this is your rightful decision as well.

Yes, your app easily delivers superior content over Cineapp which goes along with Cineapp being a dead app. Otherwise, your content lacks heavily compared to other movie apps since it's designed solely for 1 geo. This makes your app useless to me and many others. I've also noticed it likes to buffer which delivers a bad user experience.

Unfortunately, I'm not a fan of invasive Google or their proprietary products (Firebase). The only good thing they've ever created was Android and they're slowly adding restrictions with time.

These are just my opinions, nothing more than that.
