### ISSUE TITLE
[Concern] Virus Reports

### ISSUE THREAD

**Issue by DarkCrypt** [yogesh-hacker/hackflix.github.io#2]
I've uploaded the Hack Flix apk into 3 different virus scanning sites in order to retrieve any malicious reports.

Unfortunately, **2/3** scans came back as **malicious**.

More than likely these are false positives (which are quite common). This still raises security concerns and need to be addressed.

Reports:

1. VirusTotal = Malicious (2/62)
https://www.virustotal.com/gui/file/72c3128b3c9280c85f109675198711d09f35ff005ba476981f401bff6740dff5/summary
2. Pithus = Malicious (2/62)
https://beta.pithus.org/report/72c3128b3c9280c85f109675198711d09f35ff005ba476981f401bff6740dff5
3. Jotti = Clean (0/14)
https://virusscan.jotti.org/en-US/filescanjob/91hfar9859

**Comment by yogesh-hacker** [comment]
My apk is not a virus only 4 vendors marking out it as a virus and that's not big deal. Each application would have some vendors like it. Checked with Google Security Scans, its not a virus...

**Comment by DarkCrypt** [comment]
Like I said, it's more than likely false positives but it's much smarter to not only rely on Play Protect. Many users will scan an apk with VirusTotal and other tools.

**Comment by yogesh-hacker** [comment]
Firstly, I'd like to extend my gratitude for your understanding, apologize for any previous harshness, and explain that my behavior stems from being new to Android development and facing personal challenges. It's tough to accept false criticism of an app I've invested a year in.

Secondly, I've taken note of your concerns, and as an Ethical Hacker, I fully understand the importance of security. Unfortunately, due to not having access to a computer, I can't enhance the app's security immediately. However, I assure you that in the future, security will be a top priority. Despite the repository suggesting otherwise, I've developed the app as closed source. Regarding the virus total issue, it's beyond my control as the compiler defaults to debug mode despite being a release version. The IDE hasn't updated itself accordingly. You can verify this with "CodeAssist" (open source).

Thirdly, my app is specifically targeted for the Indian market.

Lastly, I'm open to building friendships. If you're interested, feel free to share your contact or social media details via businesshackerindia@gmail.com.
